### ISSUE TITLE
Preview mode timing out (UnhandledPromiseRejectionWarning)

### ISSUE THREAD

**Issue by allaire** [prismicio/prismic-client#132] opened 2020-06-11 19:32 UTC
Getting the following error sporadically when using preview mode and coming back after a while (504 Gateway Time-out
 on my side after a while).

I need to advise my team to clear their site data or open an incognito window when this happens, and this fix it for a while.

Here<s the error I get in the node.js express console:

```js
 (node:104) UnhandledPromiseRejectionWarning: Error: Unexpected status code [404] on URL https://xxx-site.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=100&access_token=xxx-977-977-977-977-9DGVdT--_vSDvv73vv71Oa1bvv73vv73vv71FJu-_ve-_vWok77-9TCQs77-977-977-9&lang=*&fetch=integration.meta_title%2Cintegration.meta_description%2Cintegration.change_frequency%2Cintegration.priority%2Cintegration.publication_date&ref=%7B%22_tracker%22%3A%22ahFfAGML%22%2C%22xxx-site.prismic.io%22%3A%7B%22preview%22%3A%22https%3A%2F%2xxx-site.prismic.io%2Fpreviews%2FXuJHuBIAACEAauBp%3AXt_IJRIAACMAYHsg%3FwebsitePreviewId%3DXD1IRxgAACcA1j2L%22%7D%7D&q=%5B%5Bat(document.type%2C%20%22integration%22)%5D%5D
app_1    | [0]     at /app/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:16417
app_1    | [0]     at process._tickCallback (internal/process/next_tick.js:68:7)
app_1    | [0] (node:104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
app_1    | [0] (node:104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm running version `2.7.1`

My express preview endpoint is as follow:

```js
const { linkResolver } = require("../lib/router");

/** @type {ExpressCallBack} */
module.exports = async (req, res, next) => {
  const { token, documentId } = req.query;

  // Make sure nginx doesn't cache response
  res.header("Vary", "*");

  if (!token) {
    next();
  } else {
    const url = await req.prismic.api.getPreviewResolver(token, documentId).resolve(linkResolver, "/");

    return res.redirect(302, url);
  }
};
```

**Comment by Gholgot** [comment] 2020-06-15 16:09
Hi @allaire, 
Can you please be more accurate on 'after a while' ?  

Reminder : the preview token expires once the saved information has been archived or published. The preview token generated is only valid for the information being previewed at that time.

**Comment by allaire** [comment] 2020-06-15 17:43
Hi @Gholgot,

Sorry I can't be more precise about any specific timeframe. It seems to happen when we are in preview mode, and then let say the person does not visit the website for a week, and then when he comeback, the site hangs and finally return a 504 gateways time-out with this error.

If this error is caused by an expired preview token, shouldn't prismic-javascript handles that gracefully?

**Comment by allaire** [comment] 2020-06-16 13:40
@Gholgot I have more information on this. The issue is caused by the cookie `io.prismic.preview`. It happens when the preview token in the cookie expires or becomes invalid, but the browser session is still active. You can duplicate by editing the "io.prismic.preview" value to anything, and refresh the browser. It should hang. To fix it, you can close the browser (because it clears the `io.prismic.preview` session cookie).

Let me know if you are able to duplicate the issue.

**Comment by Gholgot** [comment] 2020-06-16 13:50
@allaire are you using the [prismic-toolbar](https://github.com/prismicio/prismic-toolbar) ?
One of the toolbar's role is to update the preview token after a change.
If the toolbar isn't set up you will have to generate a preview manually.

**Comment by allaire** [comment] 2020-06-16 15:38
@Gholgot Yes you can see our setup here:  www.agendrix.com.

**Comment by Gholgot** [comment] 2020-06-17 07:42
@allaire ,
I'm investigating, for now, and I will give you an update by the end of my day (GMT +2).
I have enough information to investigate properly, but I will get back to you if I need more specific details.

**Comment by allaire** [comment] 2020-06-17 13:47
@Gholgot got it thank you!

**Comment by Gholgot** [comment] 2020-06-17 16:16
@allaire ,
I couldn't reproduce the bug even with all the details you provided.
I will keep you informed if any progress is made.

**Comment by allaire** [comment] 2020-07-15 19:46
@Gholgot Just letting you know that I still experience this issue on the latest version of prismic-javascript.

Like you said in your preview comment, I also get the infinite loading issue in the following case:

* I am in preview mode
* Publish my content
* Go back on the page that I was in preview mode and refresh. It hangs with this error:

```
app_1    | [0] (node:149) UnhandledPromiseRejectionWarning: Error: Unexpected status code [404] on URL https://xxx.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=100&access_token=xxxxx-977-977-977-977-9DGVdT--_vSDvv73vv71Oa1bvv73vv73vv71FJu-_ve-_vWok77-9TCQs77-977-977-9&lang=*&fetch=case_study.meta_title%2Ccase_study.meta_description%2Ccase_study.change_frequency%2Ccase_study.priority%2Ccase_study.publication_date&ref=%7B%22_tracker%22%3A%22kBcyNGVG%22%2C%xxx.prismic.io%22%3A%7B%22preview%22%3A%22https%3A%2F%xxx.prismic.io%2Fpreviews%2FXw9WBhEAACIAWv6X%3AXw9XWBEAACAAWwR6%3FwebsitePreviewId%3DXD1IRxgAACcA1j2L%22%7D%7D&q=%5B%5Bat(document.type%2C%20%22case_study%22)%5D%5D
app_1    | [0]     at /app/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:16437
app_1    | [0]     at process._tickCallback (internal/process/next_tick.js:68:7)
app_1    | [0] (node:149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
app_1    | [0] (node:149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When it hangs, I delete the cookie `io.prismic.preview` and it works after refreshing.

**Comment by MarcMcIntosh** [comment] 2020-09-17 15:00
Hi @allaire 

I took a look at your website andnoticed that there are four `prismic.io.preview`  cookies.

Could you provide us with more information about the tech stack you are using?

does curling this url return anything?
>app_1    | [0] (node:149) UnhandledPromiseRejectionWarning: Error: Unexpected status code [404] on URL https://xxx.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=100&access_token=xxxxx-977-977-977-977-9DGVdT--_vSDvv73vv71Oa1bvv73vv73vv71FJu-_ve-_vWok77-9TCQs77-977-977-9&lang=*&fetch=case_study.meta_title%2Ccase_study.meta_description%2Ccase_study.change_frequency%2Ccase_study.priority%2Ccase_study.publication_date&ref=%7B%22_tracker%22%3A%22kBcyNGVG%22%2C%xxx.prismic.io%22%3A%7B%22preview%22%3A%22https%3A%2F%xxx.prismic.io%2Fpreviews%2FXw9WBhEAACIAWv6X%3AXw9XWBEAACAAWwR6%3FwebsitePreviewId%3DXD1IRxgAACcA1j2L%22%7D%7D&q=%5B%5Bat(document.type%2C%20%22case_study%22)%5D%5D

**Comment by MarcMcIntosh** [comment] 2020-09-17 15:09
Can you show me how are you initialising `req.prismic` ?
Do you pass req similar to this example https://github.com/prismicio/nodejs-sdk/blob/master/app.js#L25

**Comment by MarcMcIntosh** [comment] 2020-09-17 15:35
Also can you that you are using the most recent version of prismic javascript?
`3.0.2`
> prismic-javascript/dist/prismic-javascript.min.js:1:16437
the `dist` directory is no longer used. as you can see here https://github.com/prismicio/prismic-javascript/blob/master/package.json

**Comment by allaire** [comment] 2020-11-02 16:23
Hi @MarcMcIntosh,

Sorry somehow I missed this notification.

So I just tried to curl a similar URL i got in a recent error today, and here's what it returns:

```
HTTP/2 404
content-type: application/json; charset=utf-8
content-length: 167
date: Mon, 02 Nov 2020 16:21:35 GMT
server: nginx
access-control-allow-origin: *
x-cache: Error from cloudfront
via: 1.1 56afed1ff867622bc96040c761f69a65.cloudfront.net (CloudFront)
x-amz-cf-pop: YUL62-C1
x-amz-cf-id: JRBLpXFyGwA_VR0yPf1hB0bz6oVe_umkSfMzfy-4DenxVqTX2BH-HA==

{"error":"This preview token has expired","oauth_initiate":"https://agendrix-site.cdn.prismic.io/auth","oauth_token":"https://agendrix-site.cdn.prismic.io/auth/token"}%
```

I confirm I'm using the latest version of prismic-javascript:

```
prismic-javascript@^3.0.0:
  version "3.0.2"
```

Here is my Express middleware that take care of `req.prismic` : 

```js
const Prismic = require("prismic-javascript");
const config = require("../config/prismic");

/** @type {ExpressCallBack} */
function prismic(req, res, next) {
  res.locals.ctx = {
    endpoint: config.apiEndpoint,
    plain: config.plainParagraphSerializer
  };

  Prismic.api(config.apiEndpoint, {
    accessToken: config.accessToken,
    req
  }).then(api => {
    req.prismic = { api };

    req.getSingle = async (type, options) => {
      const docs = await req.prismic.api.query(Prismic.Predicates.at("document.type", type), { lang: "*", ...options });

      let doc = docs.results.find(d => d.lang === req.locale.toLowerCase());

      // If there is no fr-FR document, we fallback on fr-CA one
      if (res.locals.isFrFR && !doc && docs.results_size > 1) {
        doc = docs.results.find(d => d.lang === res.locals.frCA.toLowerCase());
        doc.lang = "fr-fr";
      }

      return doc;
    };

    req.getByUID = async (type, uid, options = {}) => {
      const doc = await req.prismic.api.getByUID(type, uid, {
        lang: req.locale.toLowerCase(),
        ...options
      });

      return doc;
    };

    req.getMultiple = async (type, filters = [], options = {}) => {
      const docs = await req.prismic.api.query([Prismic.Predicates.at("document.type", type), ...filters], {
        lang: req.locale.toLowerCase(),
        ...options
      });

      return docs;
    };

    next();
  });
}

module.exports = prismic;
```

I also have the preview controller:

```js
const { linkResolver } = require("../lib/router");

/** @type {ExpressCallBack} */
module.exports = async (req, res, next) => {
  const { token, documentId } = req.query;

  // Make sure nginx doesn't cache response
  res.header("Vary", "*");

  if (!token) {
    next();
  } else {
    await req.prismic.api
      .getPreviewResolver(token, documentId)
      .resolve(linkResolver, "/")
      .then(url => {
        return res.redirect(302, url);
      })
      .catch(() => {
        return res.redirect(302, res.locals.routes.home());
      });
  }
};
```

**Comment by lihbr** [comment] 2022-01-05 10:27
Should have been fixed since, but I might be mistaken here. Closing it for now but feel free to reopen if needed. I'm really sorry for the lack of fast support here!

On another note, a brand new version of this kit has been released, you might be interested in trying it: https://prismic.io/docs/technical-reference/prismicio-client?version=v6

Have a great day!

**Closed by lihbr** 2022-01-05 10:27 UTC
Labels: bug

**Comment by allaire** [comment] 2022-01-05 14:52
@lihbr Thanks, apologies accepted :) Will give the new version a shot, I'm still running on `prismic-javascript`

**Comment by allaire** [comment] 2022-01-05 16:24
@lihbr Is there any documentation on how to upgrade for prismic-javascript (v4) to the latest prismicio/client? Express exemples are still runing on v4... https://github.com/prismicio/nodejs-blog

**Comment by lihbr** [comment] 2022-01-05 18:32
v4 and v5 are the same version (v5 just dropped Node 8 and previous), so you should be good using the migration guide to go from v4 to v6 ☺️

https://prismic.io/docs/technologies/prismic-client-v6-migration-guide
