### ISSUE TITLE
Problem with query predicates when zero documents are created

### ISSUE THREAD

**Issue by RAHMANIABOUBEKER** [prismicio/prismic-client#169] opened 2021-06-03 13:16 UTC
### Versions

- nuxt: v2.15.6
- @nuxtjs/prismic: v1.3.1
- node: v14.16.1

### Steps to reproduce
 Create content Type in Prismic and do not create documents for this content type.
Try to query document with a predicate by field
### What is Expected?

I am expecting to get the same result when any document of this type exists.

### What is actually happening?

[function at(..)] unexpected field 'my.article.categorie' on line:1 col:45 in query '[[at(document.type, \"article\")][at(my.article.categorie, \"YGzcjhIAACwAfXQ_\")][any(my.article.type, [\"article\",\"video\",\"podcast\"])]]'\n[[at(document.type, \"article\")][at(my.article.categorie, \"YGzcjhIAACwAfXQ_\")][any(my.article_investir.type, [\"article\",\"video\",\"podcast\"])]]\n                                            ^\n

**Comment by lihbr** [comment] 2021-06-03 14:20
@angeloashmore, you might want to have a look regarding that behavior in v6

**Comment by RAHMANIABOUBEKER** [comment] 2021-06-03 14:36
Hello, 

Is there any work around to avoid this from happening?

thanks.

**Comment by lihbr** [comment] 2021-06-03 16:59
Hey, if confirmed a valid issue I'm afraid there's for now not much you can do about it now apart from catching the error. We'll try to have a look at it soon ☺️

**Comment by angeloashmore** [comment] 2021-06-08 00:02
Hi @RAHMANIABOUBEKER,

I've confirmed the issue. I don't think we can do anything at the client library level to handle this. This is effectively the same error as if a user writes an incorrect predicate (for example, a non existent field or syntax error). A fix would need to be implemented in the REST API to address this issue.

Note that this occurs whenever 0 documents of a particular type are published. If the document exists in another ref, is archived, or deleted, the error still occurs.

The simplest workaround is to ensure you have at least one document of that type published.

If that is not possible, you could query all documents of that type and filter in JavaScript. If no documents of that type have been created, the query will return an empty array rather than an error.

The underlying issue most likely results from the querying logic used within the API. If it cannot find a matching field in at least one document, the field is considered non-existent. In other words, it doesn't consider the Custom Type's schema, only the created documents. This is just a hypothesis and may not reflect the actual implementation.

I've opened an internal ticket to track how we can best handle this. Thanks @RAHMANIABOUBEKER!

**Comment by RAHMANIABOUBEKER** [comment] 2021-06-08 08:06
Hello @lihbr @angeloashmore,

Thank you for your response and the explanation, 
For now I am catching the error and it is fine for me.

**Comment by lihbr** [comment] 2021-06-21 14:56
[INTERNAL]

Tracked here: https://github.com/prismicio/issue-tracker-wroom/issues/607

**Comment by lihbr** [comment] 2022-01-05 10:32
Update `01/05/2022`:

- Bumped internal tracking

**Comment by angeloashmore** [comment] 2022-03-16 19:26
Hey @RAHMANIABOUBEKER, thanks again for reporting this. I'm going to close this issue since this isn't a bug with `@prismicio/client`. We have an internal issue to track the API bug so it isn't forgotten. :)

**Closed by angeloashmore** 2022-03-16 19:26 UTC
Labels: bug, v6
