### ISSUE TITLE
getByUID call with an unexisting uid trigger a 'api_parsing_error' error.

### ISSUE THREAD

**Issue by priyaprafful** [prismicio/prismic-client#237] opened 2022-04-15 08:19 UTC
### Versions

@prismicio/client: v6 (latest)
node: v16 (latest LTS)

### Reproduction

I ran into an issue when I put incorrect or unexisting uid in the getByUID call it gives an api_parser_error. It should throw a null document or a better error.

<img width="544" alt="Screen Shot 2022-04-15 at 10 16 54" src="https://user-images.githubusercontent.com/43381242/163545048-9679c45b-f08e-428f-a05a-dafd521dfc65.png">

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Run getByUID() with an unexixting UID.

### What is expected?
It should throw a null document or a better error.

### What is actually happening?
It returns `api_parsing_error`

**Comment by lihbr** [comment] 2022-04-20 09:48
Hey there, thanks for creating an issue!

I'm not able to reproduce the error as described above, however, here's what I think is happening:
- Querying by UID using a non-existing UID yields a `PrismicError`, this is intended;
- Querying by UID using a non-existing document type yields a `ParsingError`, this is intended as the document type doesn't exist in the queried Prismic repository.

```javascript
import {
	createClient,
	PrismicError,
	ParsingError,
} from "https://cdn.skypack.dev/@prismicio/client@latest"

const client = createClient("200629-sms-hoy")

// Valid call, yields document
console.log(await client.getByUID("page", "home"))

// Unknown UID, yields PrismicError
try {
	await client.getByUID("page", "unknown")
} catch (error) {
	console.error(error instanceof PrismicError)
	console.error(error)
}

// Unknown custom type, yields ParsingError
try {
	await client.getByUID("unknown", "home")
} catch (error) {
	console.error(error instanceof ParsingError)
	console.error(error.message)
}
```

Try running this document in your browser to reproduce: [index.html.zip](https://github.com/prismicio/prismic-client/files/8520373/index.html.zip)

As this appears to be intended behavior I'll close this issue. If you think you're still experiencing a bug feel free to reopen it and provide a reproduction case.

**Closed by lihbr** 2022-04-20 09:48 UTC
Labels: bug
